[package]
name = "swaywsr"
version = "1.2.2"
description = "Change i3-wm workspace names based on its contents"
authors = ["Pedro Scaff <pedro@scaff.me>"]
repository =  "https://github.com/pedroscaff/swaywsr"
documentation =  "https://github.com/pedroscaff/swaywsr"
readme = "README.md"
keywords = ["sway-wm", "window-manager", "workspaces", "linux"]
categories = ["command-line-utilities"]
license = "MIT"
exclude = ["/assets/*"]
edition = "2018"

[badges]
travis-ci = { repository = "pedroscaff/swaywsr" }

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.8"
failure_derive = "0.1.8"
lazy_static = "1.4.0"
clap = "2.33.3"
toml = "0.5.8"
serde = { version = "1.0.123", features = ["derive"] }
swayipc = "2.7.2"
itertools = "0.10.0"

[profile.release]
strip = true
