[icons]
# font awesome
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"

[general]
separator = "  "
ignore_ending = "."
